---
- name: Unified OpenShift Remediation Rulebook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:

    - name: Trigger OOMKilled Fix
      condition: event.payload.alerts is selectattr("labels.remediation", "==", "increase-mem")
      action:
        run_job_template:
          name: "oom-remediation"
          organization: "Default"
          job_args:
            extra_vars:
              event: "{{ event }}"

    - name: Trigger Recurring OOMKilled Fix
      condition: event.payload.alerts is selectattr("labels.remediation", "==", "increase-mem-recurring")
      action:
        run_job_template:
          name: "oom-remediation"
          organization: "Default"
          job_args:
            extra_vars:
              event: "{{ event }}"

    - name: Trigger ConfigMap Desync Fix
      condition: event.payload.alerts is selectattr("labels.remediation", "==", "configmap-desync")
      action:
        run_job_template:
          name: "configmap-desync-remediation"
          organization: "Default"
          job_args:
            extra_vars:
              event: "{{ event }}"
              
    - name: Trigger CPU Throttling Fix
      condition: event.payload.alerts is selectattr("labels.remediation", "==", "cpu-throttling")
      action:
        run_job_template:
          name: "cpu-throttling-remediation"
          organization: "Default"
          job_args:
            extra_vars:
              event: "{{ event }}"
              
    - name: Trigger Deployment Regression Fix
      condition: event.payload.alerts is selectattr("labels.remediation", "==", "deployment-regression")
      action:
        run_job_template:
          name: "deployment-regression-remediation"
          organization: "Default"
          job_args:
            extra_vars:
              event: "{{ event }}"
              
    - name: Trigger Liveness Probe Fix
      condition: event.payload.alerts is selectattr("labels.remediation", "==", "liveness-probe")
      action:
        run_job_template:
          name: "liveness-probe-remediation"
          organization: "Default"
          job_args:
            extra_vars:
              event: "{{ event }}"
