---
- name: Remediation - Scale Up Memory
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Patch Deployment with more memory
      kubernetes.core.k8s:
        validate_certs: false
        state: patched
        kind: Deployment
        name: "{{ event.payload.alerts[0].labels.app }}"
        namespace: "ms-demo"
        definition:
          spec:
            template:
              spec:
                containers:
                  - name: server 
                    resources:
                      limits:
                        memory: "512Mi"
